import time
import sys
print("----------------Hack Wifi 🕷----------")
wifi_name = input ("Enter Wifi Name: ")
print("Wifi analayze :", wifi_name)
connection = int(True)
print("connection:",connection)
time.sleep(5)
Router = int(True)
print("Router:",Router)
time.sleep(6)
print("wifi password is ... :")
time.sleep(4)
print("10%")
time.sleep(4)
print("20%")
time.sleep(4)
print("30%")
time.sleep(4)
print("40%")
time.sleep(4)
print("50%")
time.sleep(4)
print("60%")
time.sleep(4)
print("70%")
time.sleep(4)
print("80%")
time.sleep(4)
print("90%")
time.sleep(4)
print("100%")
Join = input('are you ready?')
if Join == 'yes' or 'Yes':
  print("ok let's do it")
  print("1234567890")
